//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IADE
    {
        public int IadeId { get; set; }
        public Nullable<int> OgrenciId { get; set; }
        public Nullable<int> KitapId { get; set; }
        public Nullable<System.DateTime> IadeTarih { get; set; }
    
        public virtual OGRENCI OGRENCI { get; set; }
        public virtual KITAP KITAP { get; set; }
    }
}
