//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGRENCI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OGRENCI()
        {
            this.CEZALAR = new HashSet<CEZALAR>();
            this.IADE = new HashSet<IADE>();
            this.ISLEM = new HashSet<ISLEM>();
            this.MAIL1 = new HashSet<MAIL>();
            this.OGRENCIKATEGORI = new HashSet<OGRENCIKATEGORI>();
        }
    
        public int OgrenciId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string MezuniyetDurumu { get; set; }
        public Nullable<int> OkulId { get; set; }
        public Nullable<int> BolumId { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Mail { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> DurumId { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        public virtual BOLUM BOLUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CEZALAR> CEZALAR { get; set; }
        public virtual GIRIS GIRIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IADE> IADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISLEM> ISLEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAIL> MAIL1 { get; set; }
        public virtual OKUL OKUL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGRENCIKATEGORI> OGRENCIKATEGORI { get; set; }
    }
}
