//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGRENCIKATEGORI
    {
        public int Id { get; set; }
        public Nullable<int> OgrenciId { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<bool> Durumu { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        public virtual KATEGORI KATEGORI { get; set; }
        public virtual OGRENCI OGRENCI { get; set; }
    }
}
