//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OKUL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OKUL()
        {
            this.OGRENCI = new HashSet<OGRENCI>();
        }
    
        public int OkulId { get; set; }
        public string OkulAdı { get; set; }
        public Nullable<int> EkleyenId { get; set; }
        public Nullable<int> DurumId { get; set; }
        public Nullable<bool> Aktif { get; set; }
    
        public virtual GIRIS GIRIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OGRENCI> OGRENCI { get; set; }
        public virtual YONETICI YONETICI { get; set; }
    }
}
